//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameManagement/InputBinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputBinds: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputBinds()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputBinds"",
    ""maps"": [
        {
            ""name"": ""DefaultBinds"",
            ""id"": ""225de3ec-c111-47e2-89a7-9facbb0e67fb"",
            ""actions"": [
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""9a079832-b689-4e38-9a4a-1772f6d61fb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadGame"",
                    ""type"": ""Button"",
                    ""id"": ""c6ca3a5b-5b0f-4383-bc3c-467b44924550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b04b996e-d748-4e82-b4e6-5ca3560b43de"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6d66c8f0-8a49-4cfe-8050-5924b4c80782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionKeybind"",
                    ""type"": ""Button"",
                    ""id"": ""74a7b25c-c169-4b69-90da-27a336688907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractAction"",
                    ""type"": ""Button"",
                    ""id"": ""af539761-e1f8-4db2-ac83-268a7f8ab60b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryAction"",
                    ""type"": ""Button"",
                    ""id"": ""4ee4eab2-7805-441d-8773-a646f77e6d90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectItem"",
                    ""type"": ""Button"",
                    ""id"": ""90c92240-0536-46fc-ae1d-e8b4275711b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateInventory"",
                    ""type"": ""PassThrough"",
                    ""id"": ""9ee4f851-fdf3-40dd-b5a6-dcb19312cb76"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bfe60c84-cd4f-43b5-9393-98bb8e9e61bb"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""890c5cb4-95da-4f55-b69c-2203cfe46841"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""f5cdff57-137f-4bcf-bfc3-ef20aefd3c71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c109c95-28a4-459b-8f82-814b5fc8bd32"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7014916c-f167-4cd0-adc4-9f005634f28c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5afcd4aa-7ce6-49d9-8508-447996c3b2e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cd4f868c-9446-4d9c-aa56-b9ac0c6bbcbe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c939191e-59c8-42ae-8c47-fba7abdf0d88"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb5a4691-dfc5-4a0b-bebf-92175fd9d120"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cf87756-8e2f-4060-adfd-9a3d1ff4a27d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeaf8c62-8d8b-468b-8619-6a837bd52d73"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a5ca10c-c412-40d3-a52f-6e121760606d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f713d23-ab09-4b5f-8a79-cc2f98c4f652"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d23f03ab-5e13-4b4d-aa9c-3af7ce2e70b0"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3673df7-70b8-47da-8ed8-98aa440efaa6"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b05ebbc7-96e5-4eb4-9131-53562d95d00e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb8de879-24c6-41d4-b77f-a9237bd51027"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e445487-f5f1-4b4c-a1fa-84fa4fd7a2bf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47556a5d-7e0d-4b1e-b74b-e29d8c4a3df5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""c0b8c573-0fd1-4293-b69d-cbd89f2929b3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f8bd77da-8ac8-4e56-aa11-d524a5dc1da8"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d686b726-d7ee-45e0-bc7f-921f31a52869"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""a232745a-0a6c-4670-8133-c8c19fcf8842"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1ec676d5-272a-4b35-8071-b3185bf1c8f3"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""9e05830e-db47-40bb-b342-b67e49eae1e3"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""87d3a703-24fe-468d-a8c3-fce745bbb2bb"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9bc63707-1e26-4b60-b688-77624aebb8cd"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""26d58ff4-37f6-4290-a041-58696e935491"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""2224ba8b-26ed-44c1-bffb-ee931a263cc2"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""CurrentBinds"",
            ""id"": ""11065c5f-b14c-4a85-b538-7cdfa3957a4c"",
            ""actions"": [
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""2d6fa50b-b102-4fe8-b30e-6457e5a665e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadGame"",
                    ""type"": ""Button"",
                    ""id"": ""282ae98a-e69b-479e-89fd-0f3e732a39ed"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f24141f2-3f59-4a8b-8f01-8151150db53b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""e1d7eba6-b707-41b7-b0f8-7fd57ce6494f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActionKeybind"",
                    ""type"": ""Button"",
                    ""id"": ""cf0cc38d-e230-4cf9-9d34-82fdc2c7f46e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InteractAction"",
                    ""type"": ""Button"",
                    ""id"": ""e29acf2b-7cda-447b-8b07-5923610e3625"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""InventoryAction"",
                    ""type"": ""Button"",
                    ""id"": ""efc833bf-dab1-4649-bfe7-f4ba313e0f2d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectItem"",
                    ""type"": ""Button"",
                    ""id"": ""e30b7992-853c-4fb4-bfaa-4d780ac8fddd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateInventory"",
                    ""type"": ""PassThrough"",
                    ""id"": ""ad3667a0-70b5-4f46-9cf9-6c5fbaa0dda7"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""cdaad27a-ad4a-487f-a66d-ee4956e6ca03"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""136798e8-58ff-4c78-ac3a-146a71ac76f6"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""3817c1b3-8ea2-401f-95ec-c2a68ad59cbb"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""78bd55d8-c340-4173-8208-48819f07ddf6"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7d9f1680-08ae-4295-9d01-faf70aa4540f"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""45d459aa-bbdc-4839-80ea-26b73546ae57"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""31784685-6763-4694-b721-ba5a3dd55a12"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0eedda27-9919-4519-a392-2ba878bbaf35"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""828983b8-dc90-4cc0-b92f-c8eff303f960"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0fb8bc5-2c4c-41cc-be5f-fd96176a0b90"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""536de545-1efb-43cc-9948-7a1a27b6d23a"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc0d9551-5cd2-4dfc-b61f-01190d36f7c1"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""80620cb9-2686-4b08-9639-e272504bb90a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActionKeybind"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26860bef-83d0-4b1c-8445-d1f23f4f8bbc"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a140e9fa-4fb7-4d53-b4ef-d48d6fbb1891"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InteractAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5229df66-2f04-42d4-bdce-0438372ba531"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""715149ad-4385-4b0d-b8f8-864343e70cbf"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""InventoryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12016cd5-537f-4be6-ad9a-2b4c43b6868a"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4af9de91-fd3f-490c-acca-68d4de52d581"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""83852370-a259-4444-94a6-a072efbfa8c7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9876f801-9746-4ab4-8a3a-7f9b206cfe3d"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c0d42e82-4a5c-4f7d-b890-cc97b23b8e8a"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d9f7ae6b-bdc4-479f-acc7-aa95f036e50b"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""147075df-81ed-42b1-9c4d-0c2798cc6548"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""2e195b61-fdd5-4226-bb9e-679a5f498b1e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ba69077d-2358-4656-bb11-f0232cf2e36c"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""954a4d6a-a871-46f0-9edb-55eed6fbb863"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74275181-3c80-4032-8c44-d88f9cbbe898"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""6e6e3041-c45d-4042-936e-57313f656b8b"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultBinds
        m_DefaultBinds = asset.FindActionMap("DefaultBinds", throwIfNotFound: true);
        m_DefaultBinds_SaveGame = m_DefaultBinds.FindAction("SaveGame", throwIfNotFound: true);
        m_DefaultBinds_LoadGame = m_DefaultBinds.FindAction("LoadGame", throwIfNotFound: true);
        m_DefaultBinds_Walk = m_DefaultBinds.FindAction("Walk", throwIfNotFound: true);
        m_DefaultBinds_Jump = m_DefaultBinds.FindAction("Jump", throwIfNotFound: true);
        m_DefaultBinds_ActionKeybind = m_DefaultBinds.FindAction("ActionKeybind", throwIfNotFound: true);
        m_DefaultBinds_InteractAction = m_DefaultBinds.FindAction("InteractAction", throwIfNotFound: true);
        m_DefaultBinds_InventoryAction = m_DefaultBinds.FindAction("InventoryAction", throwIfNotFound: true);
        m_DefaultBinds_SelectItem = m_DefaultBinds.FindAction("SelectItem", throwIfNotFound: true);
        m_DefaultBinds_NavigateInventory = m_DefaultBinds.FindAction("NavigateInventory", throwIfNotFound: true);
        // CurrentBinds
        m_CurrentBinds = asset.FindActionMap("CurrentBinds", throwIfNotFound: true);
        m_CurrentBinds_SaveGame = m_CurrentBinds.FindAction("SaveGame", throwIfNotFound: true);
        m_CurrentBinds_LoadGame = m_CurrentBinds.FindAction("LoadGame", throwIfNotFound: true);
        m_CurrentBinds_Walk = m_CurrentBinds.FindAction("Walk", throwIfNotFound: true);
        m_CurrentBinds_Jump = m_CurrentBinds.FindAction("Jump", throwIfNotFound: true);
        m_CurrentBinds_ActionKeybind = m_CurrentBinds.FindAction("ActionKeybind", throwIfNotFound: true);
        m_CurrentBinds_InteractAction = m_CurrentBinds.FindAction("InteractAction", throwIfNotFound: true);
        m_CurrentBinds_InventoryAction = m_CurrentBinds.FindAction("InventoryAction", throwIfNotFound: true);
        m_CurrentBinds_SelectItem = m_CurrentBinds.FindAction("SelectItem", throwIfNotFound: true);
        m_CurrentBinds_NavigateInventory = m_CurrentBinds.FindAction("NavigateInventory", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultBinds
    private readonly InputActionMap m_DefaultBinds;
    private List<IDefaultBindsActions> m_DefaultBindsActionsCallbackInterfaces = new List<IDefaultBindsActions>();
    private readonly InputAction m_DefaultBinds_SaveGame;
    private readonly InputAction m_DefaultBinds_LoadGame;
    private readonly InputAction m_DefaultBinds_Walk;
    private readonly InputAction m_DefaultBinds_Jump;
    private readonly InputAction m_DefaultBinds_ActionKeybind;
    private readonly InputAction m_DefaultBinds_InteractAction;
    private readonly InputAction m_DefaultBinds_InventoryAction;
    private readonly InputAction m_DefaultBinds_SelectItem;
    private readonly InputAction m_DefaultBinds_NavigateInventory;
    public struct DefaultBindsActions
    {
        private @InputBinds m_Wrapper;
        public DefaultBindsActions(@InputBinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @SaveGame => m_Wrapper.m_DefaultBinds_SaveGame;
        public InputAction @LoadGame => m_Wrapper.m_DefaultBinds_LoadGame;
        public InputAction @Walk => m_Wrapper.m_DefaultBinds_Walk;
        public InputAction @Jump => m_Wrapper.m_DefaultBinds_Jump;
        public InputAction @ActionKeybind => m_Wrapper.m_DefaultBinds_ActionKeybind;
        public InputAction @InteractAction => m_Wrapper.m_DefaultBinds_InteractAction;
        public InputAction @InventoryAction => m_Wrapper.m_DefaultBinds_InventoryAction;
        public InputAction @SelectItem => m_Wrapper.m_DefaultBinds_SelectItem;
        public InputAction @NavigateInventory => m_Wrapper.m_DefaultBinds_NavigateInventory;
        public InputActionMap Get() { return m_Wrapper.m_DefaultBinds; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultBindsActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultBindsActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Add(instance);
            @SaveGame.started += instance.OnSaveGame;
            @SaveGame.performed += instance.OnSaveGame;
            @SaveGame.canceled += instance.OnSaveGame;
            @LoadGame.started += instance.OnLoadGame;
            @LoadGame.performed += instance.OnLoadGame;
            @LoadGame.canceled += instance.OnLoadGame;
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @ActionKeybind.started += instance.OnActionKeybind;
            @ActionKeybind.performed += instance.OnActionKeybind;
            @ActionKeybind.canceled += instance.OnActionKeybind;
            @InteractAction.started += instance.OnInteractAction;
            @InteractAction.performed += instance.OnInteractAction;
            @InteractAction.canceled += instance.OnInteractAction;
            @InventoryAction.started += instance.OnInventoryAction;
            @InventoryAction.performed += instance.OnInventoryAction;
            @InventoryAction.canceled += instance.OnInventoryAction;
            @SelectItem.started += instance.OnSelectItem;
            @SelectItem.performed += instance.OnSelectItem;
            @SelectItem.canceled += instance.OnSelectItem;
            @NavigateInventory.started += instance.OnNavigateInventory;
            @NavigateInventory.performed += instance.OnNavigateInventory;
            @NavigateInventory.canceled += instance.OnNavigateInventory;
        }

        private void UnregisterCallbacks(IDefaultBindsActions instance)
        {
            @SaveGame.started -= instance.OnSaveGame;
            @SaveGame.performed -= instance.OnSaveGame;
            @SaveGame.canceled -= instance.OnSaveGame;
            @LoadGame.started -= instance.OnLoadGame;
            @LoadGame.performed -= instance.OnLoadGame;
            @LoadGame.canceled -= instance.OnLoadGame;
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @ActionKeybind.started -= instance.OnActionKeybind;
            @ActionKeybind.performed -= instance.OnActionKeybind;
            @ActionKeybind.canceled -= instance.OnActionKeybind;
            @InteractAction.started -= instance.OnInteractAction;
            @InteractAction.performed -= instance.OnInteractAction;
            @InteractAction.canceled -= instance.OnInteractAction;
            @InventoryAction.started -= instance.OnInventoryAction;
            @InventoryAction.performed -= instance.OnInventoryAction;
            @InventoryAction.canceled -= instance.OnInventoryAction;
            @SelectItem.started -= instance.OnSelectItem;
            @SelectItem.performed -= instance.OnSelectItem;
            @SelectItem.canceled -= instance.OnSelectItem;
            @NavigateInventory.started -= instance.OnNavigateInventory;
            @NavigateInventory.performed -= instance.OnNavigateInventory;
            @NavigateInventory.canceled -= instance.OnNavigateInventory;
        }

        public void RemoveCallbacks(IDefaultBindsActions instance)
        {
            if (m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultBindsActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultBindsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultBindsActions @DefaultBinds => new DefaultBindsActions(this);

    // CurrentBinds
    private readonly InputActionMap m_CurrentBinds;
    private List<ICurrentBindsActions> m_CurrentBindsActionsCallbackInterfaces = new List<ICurrentBindsActions>();
    private readonly InputAction m_CurrentBinds_SaveGame;
    private readonly InputAction m_CurrentBinds_LoadGame;
    private readonly InputAction m_CurrentBinds_Walk;
    private readonly InputAction m_CurrentBinds_Jump;
    private readonly InputAction m_CurrentBinds_ActionKeybind;
    private readonly InputAction m_CurrentBinds_InteractAction;
    private readonly InputAction m_CurrentBinds_InventoryAction;
    private readonly InputAction m_CurrentBinds_SelectItem;
    private readonly InputAction m_CurrentBinds_NavigateInventory;
    public struct CurrentBindsActions
    {
        private @InputBinds m_Wrapper;
        public CurrentBindsActions(@InputBinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @SaveGame => m_Wrapper.m_CurrentBinds_SaveGame;
        public InputAction @LoadGame => m_Wrapper.m_CurrentBinds_LoadGame;
        public InputAction @Walk => m_Wrapper.m_CurrentBinds_Walk;
        public InputAction @Jump => m_Wrapper.m_CurrentBinds_Jump;
        public InputAction @ActionKeybind => m_Wrapper.m_CurrentBinds_ActionKeybind;
        public InputAction @InteractAction => m_Wrapper.m_CurrentBinds_InteractAction;
        public InputAction @InventoryAction => m_Wrapper.m_CurrentBinds_InventoryAction;
        public InputAction @SelectItem => m_Wrapper.m_CurrentBinds_SelectItem;
        public InputAction @NavigateInventory => m_Wrapper.m_CurrentBinds_NavigateInventory;
        public InputActionMap Get() { return m_Wrapper.m_CurrentBinds; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CurrentBindsActions set) { return set.Get(); }
        public void AddCallbacks(ICurrentBindsActions instance)
        {
            if (instance == null || m_Wrapper.m_CurrentBindsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CurrentBindsActionsCallbackInterfaces.Add(instance);
            @SaveGame.started += instance.OnSaveGame;
            @SaveGame.performed += instance.OnSaveGame;
            @SaveGame.canceled += instance.OnSaveGame;
            @LoadGame.started += instance.OnLoadGame;
            @LoadGame.performed += instance.OnLoadGame;
            @LoadGame.canceled += instance.OnLoadGame;
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @ActionKeybind.started += instance.OnActionKeybind;
            @ActionKeybind.performed += instance.OnActionKeybind;
            @ActionKeybind.canceled += instance.OnActionKeybind;
            @InteractAction.started += instance.OnInteractAction;
            @InteractAction.performed += instance.OnInteractAction;
            @InteractAction.canceled += instance.OnInteractAction;
            @InventoryAction.started += instance.OnInventoryAction;
            @InventoryAction.performed += instance.OnInventoryAction;
            @InventoryAction.canceled += instance.OnInventoryAction;
            @SelectItem.started += instance.OnSelectItem;
            @SelectItem.performed += instance.OnSelectItem;
            @SelectItem.canceled += instance.OnSelectItem;
            @NavigateInventory.started += instance.OnNavigateInventory;
            @NavigateInventory.performed += instance.OnNavigateInventory;
            @NavigateInventory.canceled += instance.OnNavigateInventory;
        }

        private void UnregisterCallbacks(ICurrentBindsActions instance)
        {
            @SaveGame.started -= instance.OnSaveGame;
            @SaveGame.performed -= instance.OnSaveGame;
            @SaveGame.canceled -= instance.OnSaveGame;
            @LoadGame.started -= instance.OnLoadGame;
            @LoadGame.performed -= instance.OnLoadGame;
            @LoadGame.canceled -= instance.OnLoadGame;
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @ActionKeybind.started -= instance.OnActionKeybind;
            @ActionKeybind.performed -= instance.OnActionKeybind;
            @ActionKeybind.canceled -= instance.OnActionKeybind;
            @InteractAction.started -= instance.OnInteractAction;
            @InteractAction.performed -= instance.OnInteractAction;
            @InteractAction.canceled -= instance.OnInteractAction;
            @InventoryAction.started -= instance.OnInventoryAction;
            @InventoryAction.performed -= instance.OnInventoryAction;
            @InventoryAction.canceled -= instance.OnInventoryAction;
            @SelectItem.started -= instance.OnSelectItem;
            @SelectItem.performed -= instance.OnSelectItem;
            @SelectItem.canceled -= instance.OnSelectItem;
            @NavigateInventory.started -= instance.OnNavigateInventory;
            @NavigateInventory.performed -= instance.OnNavigateInventory;
            @NavigateInventory.canceled -= instance.OnNavigateInventory;
        }

        public void RemoveCallbacks(ICurrentBindsActions instance)
        {
            if (m_Wrapper.m_CurrentBindsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICurrentBindsActions instance)
        {
            foreach (var item in m_Wrapper.m_CurrentBindsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CurrentBindsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CurrentBindsActions @CurrentBinds => new CurrentBindsActions(this);
    public interface IDefaultBindsActions
    {
        void OnSaveGame(InputAction.CallbackContext context);
        void OnLoadGame(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnActionKeybind(InputAction.CallbackContext context);
        void OnInteractAction(InputAction.CallbackContext context);
        void OnInventoryAction(InputAction.CallbackContext context);
        void OnSelectItem(InputAction.CallbackContext context);
        void OnNavigateInventory(InputAction.CallbackContext context);
    }
    public interface ICurrentBindsActions
    {
        void OnSaveGame(InputAction.CallbackContext context);
        void OnLoadGame(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnActionKeybind(InputAction.CallbackContext context);
        void OnInteractAction(InputAction.CallbackContext context);
        void OnInventoryAction(InputAction.CallbackContext context);
        void OnSelectItem(InputAction.CallbackContext context);
        void OnNavigateInventory(InputAction.CallbackContext context);
    }
}
