//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scripts/GameManagement/InputBinds/InputBinds.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputBinds: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputBinds()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputBinds"",
    ""maps"": [
        {
            ""name"": ""DefaultBinds"",
            ""id"": ""225de3ec-c111-47e2-89a7-9facbb0e67fb"",
            ""actions"": [
                {
                    ""name"": ""SaveGame"",
                    ""type"": ""Button"",
                    ""id"": ""9a079832-b689-4e38-9a4a-1772f6d61fb2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadGame"",
                    ""type"": ""Button"",
                    ""id"": ""c6ca3a5b-5b0f-4383-bc3c-467b44924550"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b04b996e-d748-4e82-b4e6-5ca3560b43de"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate Inventory"",
                    ""type"": ""PassThrough"",
                    ""id"": ""807d0e6e-4b3e-4a82-9bef-19fa7a5568ef"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6d66c8f0-8a49-4cfe-8050-5924b4c80782"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement Action"",
                    ""type"": ""Button"",
                    ""id"": ""74a7b25c-c169-4b69-90da-27a336688907"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Open Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""4ee4eab2-7805-441d-8773-a646f77e6d90"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select and Interact"",
                    ""type"": ""Button"",
                    ""id"": ""90c92240-0536-46fc-ae1d-e8b4275711b5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bfe60c84-cd4f-43b5-9393-98bb8e9e61bb"",
                    ""path"": ""<Keyboard>/f5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SaveGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""890c5cb4-95da-4f55-b69c-2203cfe46841"",
                    ""path"": ""<Keyboard>/f6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""f5cdff57-137f-4bcf-bfc3-ef20aefd3c71"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c109c95-28a4-459b-8f82-814b5fc8bd32"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7014916c-f167-4cd0-adc4-9f005634f28c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5afcd4aa-7ce6-49d9-8508-447996c3b2e9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""cd4f868c-9446-4d9c-aa56-b9ac0c6bbcbe"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c939191e-59c8-42ae-8c47-fba7abdf0d88"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb5a4691-dfc5-4a0b-bebf-92175fd9d120"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cf87756-8e2f-4060-adfd-9a3d1ff4a27d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aeaf8c62-8d8b-468b-8619-6a837bd52d73"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a5ca10c-c412-40d3-a52f-6e121760606d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f713d23-ab09-4b5f-8a79-cc2f98c4f652"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement Action"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b05ebbc7-96e5-4eb4-9131-53562d95d00e"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb8de879-24c6-41d4-b77f-a9237bd51027"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Open Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e445487-f5f1-4b4c-a1fa-84fa4fd7a2bf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select and Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47556a5d-7e0d-4b1e-b74b-e29d8c4a3df5"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select and Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""b61a3eb9-add3-486c-bf44-3d5377db1f6f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3d27054e-6d4b-4aef-95bd-b18bfec877d0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""f019f869-7316-44fe-8ecb-9f89163ede67"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""747e7867-1f0b-41f2-8831-17284f643585"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e2844d9f-69fa-41bc-bfbe-b215acf98ce5"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a6c8da60-6406-47ec-b4a3-731c4ee048b0"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DefaultBinds
        m_DefaultBinds = asset.FindActionMap("DefaultBinds", throwIfNotFound: true);
        m_DefaultBinds_SaveGame = m_DefaultBinds.FindAction("SaveGame", throwIfNotFound: true);
        m_DefaultBinds_LoadGame = m_DefaultBinds.FindAction("LoadGame", throwIfNotFound: true);
        m_DefaultBinds_Walk = m_DefaultBinds.FindAction("Walk", throwIfNotFound: true);
        m_DefaultBinds_NavigateInventory = m_DefaultBinds.FindAction("Navigate Inventory", throwIfNotFound: true);
        m_DefaultBinds_Jump = m_DefaultBinds.FindAction("Jump", throwIfNotFound: true);
        m_DefaultBinds_MovementAction = m_DefaultBinds.FindAction("Movement Action", throwIfNotFound: true);
        m_DefaultBinds_OpenInventory = m_DefaultBinds.FindAction("Open Inventory", throwIfNotFound: true);
        m_DefaultBinds_SelectandInteract = m_DefaultBinds.FindAction("Select and Interact", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DefaultBinds
    private readonly InputActionMap m_DefaultBinds;
    private List<IDefaultBindsActions> m_DefaultBindsActionsCallbackInterfaces = new List<IDefaultBindsActions>();
    private readonly InputAction m_DefaultBinds_SaveGame;
    private readonly InputAction m_DefaultBinds_LoadGame;
    private readonly InputAction m_DefaultBinds_Walk;
    private readonly InputAction m_DefaultBinds_NavigateInventory;
    private readonly InputAction m_DefaultBinds_Jump;
    private readonly InputAction m_DefaultBinds_MovementAction;
    private readonly InputAction m_DefaultBinds_OpenInventory;
    private readonly InputAction m_DefaultBinds_SelectandInteract;
    public struct DefaultBindsActions
    {
        private @InputBinds m_Wrapper;
        public DefaultBindsActions(@InputBinds wrapper) { m_Wrapper = wrapper; }
        public InputAction @SaveGame => m_Wrapper.m_DefaultBinds_SaveGame;
        public InputAction @LoadGame => m_Wrapper.m_DefaultBinds_LoadGame;
        public InputAction @Walk => m_Wrapper.m_DefaultBinds_Walk;
        public InputAction @NavigateInventory => m_Wrapper.m_DefaultBinds_NavigateInventory;
        public InputAction @Jump => m_Wrapper.m_DefaultBinds_Jump;
        public InputAction @MovementAction => m_Wrapper.m_DefaultBinds_MovementAction;
        public InputAction @OpenInventory => m_Wrapper.m_DefaultBinds_OpenInventory;
        public InputAction @SelectandInteract => m_Wrapper.m_DefaultBinds_SelectandInteract;
        public InputActionMap Get() { return m_Wrapper.m_DefaultBinds; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultBindsActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultBindsActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Add(instance);
            @SaveGame.started += instance.OnSaveGame;
            @SaveGame.performed += instance.OnSaveGame;
            @SaveGame.canceled += instance.OnSaveGame;
            @LoadGame.started += instance.OnLoadGame;
            @LoadGame.performed += instance.OnLoadGame;
            @LoadGame.canceled += instance.OnLoadGame;
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @NavigateInventory.started += instance.OnNavigateInventory;
            @NavigateInventory.performed += instance.OnNavigateInventory;
            @NavigateInventory.canceled += instance.OnNavigateInventory;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @MovementAction.started += instance.OnMovementAction;
            @MovementAction.performed += instance.OnMovementAction;
            @MovementAction.canceled += instance.OnMovementAction;
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @SelectandInteract.started += instance.OnSelectandInteract;
            @SelectandInteract.performed += instance.OnSelectandInteract;
            @SelectandInteract.canceled += instance.OnSelectandInteract;
        }

        private void UnregisterCallbacks(IDefaultBindsActions instance)
        {
            @SaveGame.started -= instance.OnSaveGame;
            @SaveGame.performed -= instance.OnSaveGame;
            @SaveGame.canceled -= instance.OnSaveGame;
            @LoadGame.started -= instance.OnLoadGame;
            @LoadGame.performed -= instance.OnLoadGame;
            @LoadGame.canceled -= instance.OnLoadGame;
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @NavigateInventory.started -= instance.OnNavigateInventory;
            @NavigateInventory.performed -= instance.OnNavigateInventory;
            @NavigateInventory.canceled -= instance.OnNavigateInventory;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @MovementAction.started -= instance.OnMovementAction;
            @MovementAction.performed -= instance.OnMovementAction;
            @MovementAction.canceled -= instance.OnMovementAction;
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @SelectandInteract.started -= instance.OnSelectandInteract;
            @SelectandInteract.performed -= instance.OnSelectandInteract;
            @SelectandInteract.canceled -= instance.OnSelectandInteract;
        }

        public void RemoveCallbacks(IDefaultBindsActions instance)
        {
            if (m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultBindsActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultBindsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultBindsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultBindsActions @DefaultBinds => new DefaultBindsActions(this);
    public interface IDefaultBindsActions
    {
        void OnSaveGame(InputAction.CallbackContext context);
        void OnLoadGame(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnNavigateInventory(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnMovementAction(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnSelectandInteract(InputAction.CallbackContext context);
    }
}
